# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qscBR_AJTTAZPSJbmgIKs9Gx53YbkA99
"""

import pandas as pd
from flask import Flask, jsonify

app = Flask(__name__);

dados = pd.read_csv('12-18 - Criando API no Python.csv', sep = ',');

@app.route('/')
def homepage():
 return 'A API ESTA NO AR'

@app.route('/total_vendas_geral')
def infoVendas():
  total_vendas = dados['Vendas'].sum()
  total_vendas = round(total_vendas,1)
  max_vendas = dados['Vendas'].max()
  max_vendas = round(max_vendas,1)
  min_vendas = dados['Vendas'].min()
  min_vendas = round(min_vendas,1)
  resposta = {'total_vendas': total_vendas, 'maior_venda': max_vendas,'menor_venda' : min_vendas}
  return jsonify(resposta)

app.run(host='0.0.0.0')